name: CI

on:
  - pull_request
  - push

jobs:
  build:
    name: PHP ${{ matrix.php-version }}_${{ matrix.stability }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.0', '8.1', '8.2']
        stability: [lowest, stable]
        include:
          - php-version: '8.3'
            flags: "--ignore-platform-req=php"
            stability: stable

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: xdebug
      - name: Install dependencies
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer update --prefer-${{ matrix.stability }} --no-progress ${{ matrix.flags }}
      - name: Install Titipan
        if: ${{ matrix.php-version >= 8.0 }}
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: |
            composer require realodix/change-case
            composer require realodix/readtime -W
      - name: Execute tests
        run: ./vendor/bin/phpunit
